"""create data related tables

Revision ID: 06bcebb14280
Revises: f5e246047393
Create Date: 2025-10-19 22:48:05.948400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bcebb14280'
down_revision: Union[str, Sequence[str], None] = 'f5e246047393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_description'), 'data_sources', ['description'], unique=True)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_table('feature_sets',
    sa.Column('feature_type', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('hf_repo_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hf_repo_id')
    )
    op.create_index(op.f('ix_feature_sets_feature_type'), 'feature_sets', ['feature_type'], unique=True)
    op.create_index(op.f('ix_feature_sets_id'), 'feature_sets', ['id'], unique=False)
    op.create_table('historical_periods',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('limit_lower', sa.Float(), nullable=False),
    sa.Column('limit_upper', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_periods_id'), 'historical_periods', ['id'], unique=False)
    op.create_index(op.f('ix_historical_periods_name'), 'historical_periods', ['name'], unique=True)
    op.create_table('pottery_items',
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pottery_items_id'), 'pottery_items', ['id'], unique=False)
    op.create_index(op.f('ix_pottery_items_object_id'), 'pottery_items', ['object_id'], unique=True)
    op.create_table('chronology_labels',
    sa.Column('start_year', sa.Float(), nullable=False),
    sa.Column('end_year', sa.Float(), nullable=False),
    sa.Column('midpoint_year', sa.Float(), nullable=False),
    sa.Column('year_range', sa.Float(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('pottery_item_id', sa.Integer(), nullable=True),
    sa.Column('historical_period_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['historical_period_id'], ['historical_periods.id'], ),
    sa.ForeignKeyConstraint(['pottery_item_id'], ['pottery_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chronology_labels_id'), 'chronology_labels', ['id'], unique=False)
    op.create_table('pottery_items_in_feature_sets',
    sa.Column('pottery_item_id', sa.Integer(), nullable=True),
    sa.Column('feature_set_id', sa.Integer(), nullable=True),
    sa.Column('feature_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], ),
    sa.ForeignKeyConstraint(['pottery_item_id'], ['pottery_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pottery_items_in_feature_sets_id'), 'pottery_items_in_feature_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pottery_items_in_feature_sets_id'), table_name='pottery_items_in_feature_sets')
    op.drop_table('pottery_items_in_feature_sets')
    op.drop_index(op.f('ix_chronology_labels_id'), table_name='chronology_labels')
    op.drop_table('chronology_labels')
    op.drop_index(op.f('ix_pottery_items_object_id'), table_name='pottery_items')
    op.drop_index(op.f('ix_pottery_items_id'), table_name='pottery_items')
    op.drop_table('pottery_items')
    op.drop_index(op.f('ix_historical_periods_name'), table_name='historical_periods')
    op.drop_index(op.f('ix_historical_periods_id'), table_name='historical_periods')
    op.drop_table('historical_periods')
    op.drop_index(op.f('ix_feature_sets_id'), table_name='feature_sets')
    op.drop_index(op.f('ix_feature_sets_feature_type'), table_name='feature_sets')
    op.drop_table('feature_sets')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_description'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
