"""create feature set versions table

Revision ID: 20251231_1233
Revises: 20251231_1152
Create Date: 2025-12-31 12:33:58.241793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251231_1233'
down_revision: Union[str, Sequence[str], None] = '20251231_1152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_set_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_set_id', sa.Integer(), nullable=False),
    sa.Column('hf_commit_hash', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_set_versions_hf_commit_hash'), 'feature_set_versions', ['hf_commit_hash'], unique=False)
    op.create_index(op.f('ix_feature_set_versions_id'), 'feature_set_versions', ['id'], unique=False)
    op.add_column('pottery_items_in_feature_sets', sa.Column('feature_set_version_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pottery_items_in_feature_sets_feature_set_id_fkey'), 'pottery_items_in_feature_sets', type_='foreignkey')
    op.create_foreign_key(None, 'pottery_items_in_feature_sets', 'feature_set_versions', ['feature_set_version_id'], ['id'])
    op.drop_column('pottery_items_in_feature_sets', 'feature_set_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pottery_items_in_feature_sets', sa.Column('feature_set_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pottery_items_in_feature_sets', type_='foreignkey')
    op.create_foreign_key(op.f('pottery_items_in_feature_sets_feature_set_id_fkey'), 'pottery_items_in_feature_sets', 'feature_sets', ['feature_set_id'], ['id'])
    op.drop_column('pottery_items_in_feature_sets', 'feature_set_version_id')
    op.drop_index(op.f('ix_feature_set_versions_id'), table_name='feature_set_versions')
    op.drop_index(op.f('ix_feature_set_versions_hf_commit_hash'), table_name='feature_set_versions')
    op.drop_table('feature_set_versions')
    # ### end Alembic commands ###
