"""create training runs tables remove training flag

Revision ID: 20251228_1401
Revises: 20251221_1552
Create Date: 2025-12-28 14:01:08.188802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251228_1401'
down_revision: Union[str, Sequence[str], None] = '20251221_1552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_strategy', sa.String(), nullable=False),
    sa.Column('random_state', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pottery_items_in_training_runs',
    sa.Column('training_run_id', sa.Integer(), nullable=False),
    sa.Column('pottery_item_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.Enum('train', 'val', 'test', name='dataset_split'), nullable=False),
    sa.ForeignKeyConstraint(['pottery_item_id'], ['pottery_items.id'], ),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('training_run_id', 'pottery_item_id')
    )
    op.add_column('model_versions', sa.Column('training_run_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model_versions', 'training_runs', ['training_run_id'], ['id'])
    op.drop_column('pottery_items', 'in_training_set')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pottery_items', sa.Column('in_training_set', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.drop_column('model_versions', 'training_run_id')
    op.drop_table('pottery_items_in_training_runs')
    op.drop_table('training_runs')
    # ### end Alembic commands ###
