"""edit feature set columns

Revision ID: 20251231_1152
Revises: 20251228_1401
Create Date: 2025-12-31 11:52:54.551227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251231_1152'
down_revision: Union[str, Sequence[str], None] = '20251228_1401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_sets', sa.Column('path_features', sa.String(), nullable=False))
    op.add_column('feature_sets', sa.Column('path_vectorizer', sa.String(), nullable=True))
    op.alter_column('feature_sets', 'hf_repo_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('feature_sets', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_sets', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('feature_sets', 'hf_repo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('feature_sets', 'path_vectorizer')
    op.drop_column('feature_sets', 'path_features')
    # ### end Alembic commands ###
