"""add training set flag remove valid flag

Revision ID: 20251221_1552
Revises: 20251221_1305
Create Date: 2025-12-21 15:52:37.618853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251221_1552'
down_revision: Union[str, Sequence[str], None] = '20251221_1305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chronology_labels', 'valid')
    op.add_column('pottery_items', sa.Column('in_training_set', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pottery_items', 'in_training_set')
    op.add_column('chronology_labels', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
