"""remove path fields from models

Revision ID: 20260102_1319
Revises: 20260101_1929
Create Date: 2026-01-02 13:19:55.480988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260102_1319'
down_revision: Union[str, Sequence[str], None] = '20260101_1929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'model_path')
    op.drop_column('models', 'config_path')
    op.drop_column('models', 'metadata_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('metadata_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('config_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('model_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
