"""simplify feature sets

Revision ID: 20260101_1705
Revises: 20251231_1233
Create Date: 2026-01-01 17:05:07.964070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260101_1705'
down_revision: Union[str, Sequence[str], None] = '20251231_1233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_set_versions_hf_commit_hash'), table_name='feature_set_versions')
    op.drop_index(op.f('ix_feature_set_versions_id'), table_name='feature_set_versions')
    op.drop_table('pottery_items_in_feature_sets')
    op.drop_table('feature_set_versions')
    op.add_column('feature_sets', sa.Column('current_version', sa.String(), nullable=False))
    op.drop_column('feature_sets', 'path_vectorizer')
    op.drop_column('feature_sets', 'path_features')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_sets', sa.Column('path_features', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('feature_sets', sa.Column('path_vectorizer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('feature_sets', 'current_version')
    op.create_table('pottery_items_in_feature_sets',
    sa.Column('pottery_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('feature_set_version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_set_version_id'], ['feature_set_versions.id'], name=op.f('pottery_items_in_feature_sets_feature_set_version_id_fkey')),
    sa.ForeignKeyConstraint(['pottery_item_id'], ['pottery_items.id'], name=op.f('pottery_items_in_feature_sets_pottery_item_id_fkey')),
    sa.PrimaryKeyConstraint('pottery_item_id', 'feature_set_version_id', name=op.f('pottery_items_in_feature_sets_pk'))
    )
    op.create_table('feature_set_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hf_commit_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name=op.f('feature_set_versions_feature_set_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_set_versions_pkey'))
    )
    op.create_index(op.f('ix_feature_set_versions_id'), 'feature_set_versions', ['id'], unique=False)
    op.create_index(op.f('ix_feature_set_versions_hf_commit_hash'), 'feature_set_versions', ['hf_commit_hash'], unique=False)
    # ### end Alembic commands ###
