"""simplify model version

Revision ID: 20260101_1929
Revises: 20260101_1705
Create Date: 2026-01-01 19:29:49.844673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260101_1929'
down_revision: Union[str, Sequence[str], None] = '20260101_1705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('version', sa.String(), nullable=False))
    op.drop_index(op.f('ix_model_versions_hf_commit_hash'), table_name='model_versions')
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.drop_column('model_versions', 'hf_commit_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('hf_commit_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.create_index(op.f('ix_model_versions_hf_commit_hash'), 'model_versions', ['hf_commit_hash'], unique=False)
    op.drop_column('model_versions', 'version')
    # ### end Alembic commands ###
